# Generated by Django 2.2.6 on 2020-04-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active',
        ),
    ]
