# Generated by Django 2.2.6 on 2020-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_delete_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
