# Generated by Django 2.2.6 on 2019-11-10 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_followers_chat_id'),
        ('chat', '0002_auto_20191003_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=800)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('From', models.ForeignKey(on_delete=None, related_name='fromUnread', to='account.Users')),
                ('To', models.ForeignKey(on_delete=None, related_name='toUnread', to='account.Users')),
                ('chat_id', models.ForeignKey(on_delete=None, related_name='JoinsUnread', to='account.Followers')),
            ],
            options={
                'ordering': ('-time_date',),
            },
        ),
        migrations.CreateModel(
            name='ReadMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=800)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('From', models.ForeignKey(on_delete=None, related_name='fromRead', to='account.Users')),
                ('To', models.ForeignKey(on_delete=None, related_name='toRead', to='account.Users')),
                ('chat_id', models.ForeignKey(on_delete=None, related_name='JoinsRead', to='account.Followers')),
            ],
            options={
                'ordering': ('-time_date',),
            },
        ),
    ]
